name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: raju15022004
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish Snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan output

          git rm -rf . || true

          cp -r dist/* .

          git add .
          git commit -m "Update contribution snake" || true

          git push --force origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
